/*
 * timer.h
 *
 *  Created on: 2015/6/25
 *      Author: jk
 */

#ifndef USER_ELECTROMBILE_TIMER_H_
#define USER_ELECTROMBILE_TIMER_H_

#include <eat_timer.h>

#define TIMER_GPS  	    EAT_TIMER_1
#define TIMER_WATCHDOG  EAT_TIMER_2
#define TIMER_VIBRATION EAT_TIMER_3
#define TIMER_LOOP      EAT_TIMER_4
//#define TIMER_GPS_SEND  EAT_TIMER_5
//#define TIMER_SEEK  	EAT_TIMER_6
//#define TIMER_SOCKET	EAT_TIMER_7
#define TIMER_HEARTBEAT	EAT_TIMER_8
#define TIMER_SEEKAUTOOFF EAT_TIMER_9
#define TIMER_UPDATE_RTC EAT_TIMER_10
#define TIMER_MOVE_ALARM EAT_TIMER_11
#define TIMER_VOLTAGE_GET EAT_TIMER_12


#endif /* USER_ELECTROMBILE_TIMER_H_ */
